dtb-$(CONFIG_MVA_OVERLAY_BD71815_SIMPLE_GAUGE_TEST) += bd71815_bbb_gauge_test.dtbo bd71815_bbb_ic_test.dtbo
DTC_FLAGS += -@
#PHONY += test_overlay_blobs

#test_overlay_blobs: $(dtbo-y)

#%.dtbo:
#	echo "dtc -O dtb -o $@ -b 0 -@ $*.dts"
#	dtc -O dtb -o $@ -b 0 -@ $*.dts
#	sleep 10

#dtb-$(CONFIG_MVA_OVERLAY_BD71815_SIMPLE_GAUGE_TEST) += bd71815_bbb_gauge_test.dtbo bd71815_bbb_ic_test.dtbo
